CREATE TABLE if not exists "Franchises"."Franchises" (
	"FranchiseId" bigserial NOT NULL,
	"Url" text NULL,
	"Title" varchar(200) NOT NULL,
	"Text" varchar(400) NOT NULL,
	"Price" numeric NULL DEFAULT 0,
	"DateCreate" timestamp NULL DEFAULT now(),
	"TextDoPrice" varchar(100) NOT NULL,
	"Category" varchar(100) NOT NULL DEFAULT ''::character varying,
	"SubCategory" varchar(100) NOT NULL
	"City" varchar(200) NULL,
	"ViewBusiness" varchar(200) NULL,
	"IsGarant" bool NOT NULL DEFAULT false,
	"ProfitPrice" numeric NULL,
	"Status" varchar(200) NULL,
	"GeneralInvest" numeric NOT NULL DEFAULT 0,
	"LumpSumPayment" numeric NOT NULL DEFAULT 0,
	"Royalty" numeric NOT NULL DEFAULT 0,
	"Payback" int4 NOT NULL DEFAULT 0,
	"ProfitMonth" numeric NOT NULL DEFAULT 0,
	"LaunchDate" int4 NOT NULL DEFAULT 0,
	"ActivityDetail" text NULL,
	"InvestInclude" json NOT NULL DEFAULT '{}'::json,
	"BaseDate" int4 NOT NULL DEFAULT date_part('year'::text, now()),
	"YearStart" int4 NOT NULL DEFAULT date_part('year'::text, now()),
	"DotCount" int4 NOT NULL DEFAULT 0,
	"BusinessCount" int4 NOT NULL DEFAULT 0,
	"Peculiarity" varchar(200) NULL,
	"NameFinModelFile" varchar(400) NULL,
	"NamePresentFile" varchar(400) NULL,
	"NameFranchisePhoto" varchar(400) NULL,
	"PaymentDetail" varchar(400) NOT NULL DEFAULT ''::character varying,
	"NameFinIndicators" varchar(200) NULL,
	"FinIndicators" json NULL DEFAULT '{}'::json,
	"TrainingDetails" varchar(400) NOT NULL DEFAULT ''::character varying,
	"TrainingPhotoName" text NULL,
	"FranchisePacks" json NULL DEFAULT '{}'::json,
	"UrlVideo" text NULL DEFAULT ''::text,
	"Reviews" json NULL DEFAULT '{}'::json,
	"UrlLogo" text null,
	CONSTRAINT "Franchises_pkey" PRIMARY KEY ("FranchiseId"),
	"UserId" text references dbo."Users"("Id")
);
